# Generated by Django 5.1.3 on 2024-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
