# Generated by Django 5.1.3 on 2024-11-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0007_alter_resume_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='userid',
        ),
    ]
