# Generated by Django 5.1.3 on 2024-11-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_rename_user_resume_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='userid',
        ),
    ]
