# Generated by Django 5.1.3 on 2024-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_remove_resume_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.CharField(default='user1', max_length=255),
        ),
    ]
