# Generated by Django 5.1.3 on 2024-11-17 06:53

import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0011_resume_created_at_resume_resume_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='gpa',
            new_name='gpapercentage',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=month.models.MonthField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=month.models.MonthField(null=True),
        ),
    ]
